# Change these first
owner: fitzwilliammuseum # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: Main website
    url: https://fitzmuseum.cam.ac.uk
  - name: Collection
    url: https://data.fitzmuseum.cam.ac.uk
  - name: Human Touch
    url: https://human-touch.fitzmuseum.cam.ac.uk
  - name: Coffins
    url: http://egyptiancoffins.org
  - name: Winsor and Newton
    url: https://winsorandnewton.fitzmuseum.cam.ac.uk/
  - name: Beyond the Label
    url: https://beyondthelabel.fitzmuseum.cam.ac.uk/
  - name: Creative Economy
    url: https://creative-economy.fitzmuseum.cam.ac.uk/
  - name: Do Not Touch
    url: https://do-not-touch.fitzmuseum.cam.ac.uk
  - name: Feast and Fast
    url: https://feast-and-fast.fitzmuseum.cam.ac.uk 
  - name: Tickets
    url: https://tickets.museums.cam.ac.uk
  - name: UCM
    url: https://museums.cam.ac.uk
  - name: Schools project
    url: http://schools.fitzmuseum.cam.ac.uk
  - name: Content API
    url: https://content.fitz.ms
  - name: Public CIIM
    url: https://api.fitz.ms
  - name: Kunisada 
    url: https://kunisada-and-kabuki.fitzmuseum.cam.ac.uk
  - name: Mapping Antiquity
    url: https://mapping-antiquity.fitzmuseum.cam.ac.uk
  - name: Portrait Miniatures
    url: https://unlocking-miniatures.fitzmuseum.cam.ac.uk
  - name: A museum of relationships
    url: https://amor.fitz.ms
  - name: URL shortener
    url: https://fitz.ms
  - name: Data Islands 
    url: https://data-islands.fitzmuseum.cam.ac.uk
  - name: Being an Islander 
    url: https://islander.fitzmuseum.cam.ac.uk
 
status-website:
  cname: uptime.fitz.ms
  #baseUrl: /uptime # where "repo" is your repository name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FitzUptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ""
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
